apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cts-inventory
  name: REPLACEME_NAME
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi