kind: ConfigMap
apiVersion: v1
metadata:
  name: REPLACEME_NAME
  namespace: cts-inventory
data:
  database.json: |
    {
        "REPLACEME_ENVIRONMENT": {
        "username": "cts",
        "password": "REPLACEME_PASSWORD",
        "database": "REPLACEME_ENVIRONMENT",
        "host": "REPLACEME_HOST",
        "dialect": "mysql",
        "operatorsAliases": false
    }
  passwords.json: |
    {
      "development": {
        "saltRounds": 12
      },
      "test": {
        "saltRounds": 12
      },
      "production": {
        "saltRounds": 12
      }
    }
  redis.json: |
    {
      "REPLACEME_ENVIRONMENT": {
        "host": "REPLACEME_HOST",
        "port": 6379,
        "db": 0
      }
    }
  session.json: |
    {
      "REPLACEME_ENVIRONMENT": {
        "sessionSecrets": ["REPLACEME_SESSION_PASSWORD"]
      }
    }